# Generated by Django 4.2.6 on 2023-10-31 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='message',
            new_name='feedback',
        ),
    ]
