# Generated by Django 4.2.6 on 2023-11-01 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_rename_message_student_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='lastname',
            new_name='father_name',
        ),
    ]
