# Generated by Django 5.0.1 on 2024-02-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_student_email_alter_student_father_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'subscribe',
            },
        ),
    ]
