# Generated by Django 4.0.2 on 2024-02-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subscribe',
        ),
    ]
